apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blue-green-ingress
  namespace: blue-green-deployment
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/actions.forward-to-canary: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"service-blue","servicePort":"80","weight":80},{"serviceName":"service-green","servicePort":"80","weight":20}]}}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forward-to-canary
                port:
                  name: use-annotation
  # Uncomment the following section if you want to enable SSL
  # tls:
  #   - hosts:
  #       - your-domain.com
  #     secretName: tls-secret