apiVersion: v1
kind: Service
metadata:
  name: service-green
  namespace: blue-green-deployment
  labels:
    app: my-python-app
    version: green
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: my-python-app
    version: green